import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Forçar tema escuro imediatamente
                document.documentElement.setAttribute('data-theme', 'dark');
                document.documentElement.classList.add('dark');
                localStorage.setItem('theme', 'dark');
                
                // Sobrescrever matchMedia para sempre retornar tema escuro
                const originalMatchMedia = window.matchMedia;
                window.matchMedia = function(query) {
                  if (query.includes('prefers-color-scheme')) {
                    return {
                      matches: query.includes('dark') ? true : false,
                      media: query,
                      onchange: null,
                      addListener: function() {},
                      removeListener: function() {},
                      addEventListener: function() {},
                      removeEventListener: function() {},
                      dispatchEvent: function() { return false; },
                    };
                  }
                  return originalMatchMedia.call(this, query);
                };
                
                // Forçar color-scheme no estilo
                const style = document.createElement('style');
                style.innerHTML = \`
                  :root { color-scheme: dark !important; }
                  html { color-scheme: dark !important; }
                \`;
                document.head.appendChild(style);
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
